### ISSUE TITLE
Able to run terraform plan without conftest

### ISSUE THREAD

**Issue by jarnohenneman** [cds-snc/terraform-plan#195]
Is it possible to run terraform plan without conftest?

```
# Setup Terraform, Terragrunt, and Conftest
- name: Setup terraform tools
  uses: cds-snc/terraform-tools-setup@v1
  env:
    #   CONFTEST_VERSION: 0.30.0
    TERRAFORM_VERSION: 1.4.6
    TERRAGRUNT_VERSION: 0.45.10
  #   TF_SUMMARIZE_VERSION: 0.2.3

- name: Terragrunt plan
  uses: cds-snc/terraform-plan@v3
  with:
    directory: ./terraform
    comment-delete: "true"
    github-token: "${{ secrets.GITHUB_TOKEN }}"
    terragrunt: "true"
```

Resulting in failing pipelines;

```
Plan changes

✅   Terraform Init: success
✅   Terraform Validate: success
✅   Terraform Format: success
✅   Terraform Plan: success
❌   Conftest: failed

Plan: 5 to add, 0 to change, 0 to destroy

Show summary
Show plan
Show Conftest results
```

**Comment by patheard** [comment]
Yup, it's possible thanks to #173:
```yaml
- name: Terragrunt plan
  uses: cds-snc/terraform-plan@v3
  with:
    directory: ./terraform
    comment-delete: "true"
    github-token: "${{ secrets.GITHUB_TOKEN }}"
    skip-conftest: "true"
    terragrunt: "true"
```

I'll get the docs updated with this change.
