### ISSUE TITLE
Bug: terraform show output failing to parse as JSON

### ISSUE THREAD

**Issue by patheard** [cds-snc/terraform-plan#28]
cds-snc/forms-staging-terraform#34 is getting the following error when using the action:
```sh
SyntaxError: Unexpected token c in JSON at position 1
    at JSON.parse (<anonymous>)
    at action (/home/runner/work/_actions/cds-snc/terraform-plan/v1.0.4/webpack:/terraform-plan/src/action.js:76:1)
    at /home/runner/work/_actions/cds-snc/terraform-plan/v1.0.4/webpack:/terraform-plan/src/index.js:16:1
    at /home/runner/work/_actions/cds-snc/terraform-plan/v1.0.4/dist/index.js:15326:3
    at Object.<anonymous> (/home/runner/work/_actions/cds-snc/terraform-plan/v1.0.4/dist/index.js:15329:12)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
```
Action run with the failure:
https://github.com/cds-snc/forms-staging-terraform/runs/2955722574?check_suite_focus=true

**Comment by patheard** [comment]
Error is being caused by the `hashicorp/setup-terraform@v1` action's Terraform wrapper output.  Fix is to disable the wrapper like so:

```yaml
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ~0.14.0
          terraform_wrapper: false
```

Action docs should also be updated and if possible, a check should be added for the `terraform_wrapper`.
