### ISSUE TITLE
Enhancement: add secret scanning to PR plan comment

### ISSUE THREAD

**Issue by patheard** [cds-snc/terraform-plan#362]
# Summary
Add secret detection to the TF plan comment before it is posted to the PR.   If a secret is found, redact its value and put a warning on the plan comment.

**Comment by KingBain** [comment]
For clarity would the secrets be coming from ? 

Our approach with secrets is to leverage a couple different methods.

making specific fields/variables as sensitive(even if theyre not)

```
variable "resource_group_name" {
  description = "The resource group for the DNS zone and backend"
  type        = string
  sensitive   = true
}
```

not tracking certain values set my backend mgmt groups and policies

```
resource "azurerm_dns_cname_record" "sds_canada_ca_cname_www" {
  name                = "www"
  zone_name           = azurerm_dns_zone.sds_canada_ca_zone.name
  resource_group_name = var.resource_group_name
  ttl                 = 3600
  record              = "sds.canada.ca"

  lifecycle {
    ignore_changes = [tags] # <--
  }
}

```


and I guess finally just scanning the entire code base with a tool loike truffle hog.

```
---
name: Secret Scan

on:
  push:
  pull_request:

permissions: read-all

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with shallow clone
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: Run TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
```

are you looking for tfstate file scanning ?
