### ISSUE TITLE
Ability to pass in -var-file arguments

### ISSUE THREAD

**Issue by eehret** [cds-snc/terraform-plan#444]
While using the most excellent terraform-plan action recently I noticed that it doesn't have a way to pass in `-var-file` arguments.

The deployment I was trying to run (details of which we inherited from a 3rd party) made heavy use of `-var-file` arguments, so it would have been nice if the action had the ability to accept them.

In the end I worked around it by adding all of the variables that were in the tfvar files into Github Environment vars instead and referenced them from there.  It worked out, but took a bit of extra time to set up.

I guess I would have similar feedback for `terraform-apply` if that action also doesn't have the ability to take `-var-file` arguments.

Maybe it would be good to implement a generic way to receive arguments, similar to what was done for the init.  That way it could be used for other things besides `-var-file`.

**Comment by patheard** [comment]
Much appreciated for the suggestion - let me look at this PR that we have open that could likely make that work for you:
- https://github.com/cds-snc/terraform-plan/pull/322

Should have time later this week 🤞🏻

**Comment by eehret** [comment]
@patheard Ah!   Sorry, I didn't think to look through the PRs.   Yes, looks like that one is intended to solve the same thing.  Thank you!

**Comment by patheard** [comment]
Decided to make a dedicate arg for it - should be able to get this merged and ready by early next week 🤞🏻

**Comment by patheard** [comment]
There we go, I flip-flopped and went back to a generic arg to set `terraform plan` options.
- https://github.com/cds-snc/terraform-plan/releases/tag/v3.4.0

You can add custom args like so:
```yml
- name: Terraform plan with variable file
  uses: cds-snc/terraform-plan
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    terraform-plan: |
      -var-file="path/to/terraform.tfvars"
```
