### ISSUE TITLE
Issue with conftest-checks SSH URL

### ISSUE THREAD

**Issue by DT-NIKOLAR** [cds-snc/terraform-plan#450]
Since yesterday, we have been encountering the following error when using the cds-snc/terraform-plan@v3 GitHub Action:
```
Error: running test: update policies: client get: download not supported for scheme 'gitgit.i.my-github-url.com'
Error: The following commands failed:
conftest test plan.json --no-color --update gitgit.i.my-github-url.com:my-org/policy-checks.git//aws_terraform
```

Below is how we are calling the terraform-plan Action in our workflow:

```yaml
- name: Terraform Plan for ${{ inputs.module }}
  uses: cds-snc/terraform-plan@v3
  with:
    comment-delete: true
    comment: ${{ github.event_name == 'pull_request' && true || false }}
    comment-title: ${{ inputs.module }}
    directory: ./${{ inputs.module }}
    terragrunt: true
    github-token: ${{ secrets.token }}
    conftest-checks: git@git.i.my-github-url.com:my-org/policy-checks.git//aws_terraform
```

The issue appears to be caused by the following change in this [PR](https://github.com/cds-snc/terraform-plan/pull/445/files#diff-3eff2eb784c259a70aa99b331bdf2de36ef13b78240a7789e3e530e0f639f817R50)
```
- const conftestChecks = core.getInput("conftest-checks");
+ const conftestChecks = sanitizeInput(core.getInput("conftest-checks"));
```

The sanitizeInput function removes certain characters from the input based on the allowedChars regex. Here is the relevant code:

```
function sanitizeInput(input, options = {}) {
  const { allowEmpty = true, allowedChars = /[^a-zA-Z0-9\-_/.+=:'"]/g } =
    options;

  // Check if the input is empty
  if (!input) {
    return allowEmpty ? "" : null;
  }

  return input.replace(allowedChars, "");
}

function parseInputInt(str, def) {
  const parsed = parseInt(str, 10);
  if (isNaN(parsed)) {
    return def;
  }
  return parsed;
}
```

Since we use SSH URLs for our conftest-checks repository, the `@` character is being stripped out by the sanitizeInput function, causing the error.

Can you please update the allowedChars regex in the sanitizeInput function to include the @ character? 

Thanks for your help!
